env:
  global:
    - CC_TEST_REPORTER_ID=588815f4040ad6bd6cebdb9af94fa7b5996a83bc6915845a3fb1d6da8ae33695
    - JRUBY_OPTS="--debug"
language: ruby
rvm:
  - jruby-9.2.12.0
jobs:
  include:
    - os: osx
      before_script:
        - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-darwin-amd64 > ./cc-test-reporter
        - chmod +x ./cc-test-reporter
        - ./cc-test-reporter before-build
      script:
        - bundle exec rake
      after_script:
        - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
        - ruby -e "$(curl -s https://undercover-ci.com/uploader.rb)" -- --repo AndyObtiva/glimmer-cw-video --commit $TRAVIS_COMMIT --lcov coverage/lcov/glimmer-cw-video.lcov
